# Development Configuration for Opinion Market API
database:
  url: "sqlite:///./opinion_market.db"
  pool_size: 20
  max_overflow: 30
  pool_timeout: 30
  pool_recycle: 3600
  echo: false
  ssl_mode: "prefer"

redis:
  url: "redis://localhost:6379"
  max_connections: 100
  socket_timeout: 5
  socket_connect_timeout: 5
  retry_on_timeout: true
  health_check_interval: 30

security:
  secret_key: "your-secret-key-change-in-production"
  algorithm: "HS256"
  access_token_expire_minutes: 1440
  refresh_token_expire_days: 30
  password_min_length: 8
  password_require_special: true
  password_require_numbers: true
  max_login_attempts: 5
  lockout_duration_minutes: 15
  rate_limit_requests: 100
  rate_limit_window: 60

api:
  title: "Opinion Market API"
  version: "2.0.0"
  description: "Advanced prediction market platform"
  docs_url: "/docs"
  redoc_url: "/redoc"
  openapi_url: "/openapi.json"
  cors_origins: ["*"]
  cors_allow_credentials: true
  cors_allow_methods: ["*"]
  cors_allow_headers: ["*"]

logging:
  level: "INFO"
  format: "json"
  file_path: "logs/app.log"
  max_file_size: 10485760
  backup_count: 5
  enable_console: true
  enable_file: true
  enable_remote: false

monitoring:
  enable_metrics: true
  metrics_port: 9090
  enable_health_checks: true
  health_check_interval: 30
  enable_tracing: true
  enable_profiling: false
  profiling_port: 6060

cache:
  default_ttl: 3600
  max_size: 1000
  enable_compression: true
  compression_level: 6
  enable_persistence: false
  persistence_path: "cache/data"

ai:
  enable_predictions: true
  model_update_interval: 3600
  prediction_cache_ttl: 1800
  max_prediction_history: 10000
  enable_sentiment_analysis: true
  sentiment_update_interval: 300

blockchain:
  enable_integration: false
  network: "ethereum"
  rpc_url: null
  private_key: null
  contract_address: null
  gas_limit: 200000
  gas_price: 20

environment: "development"
